# Generated by Django 3.0.6 on 2020-06-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200616_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDate', models.DateField()),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField()),
                ('feedback', models.TextField()),
                ('reason', models.TextField(max_length=1000)),
                ('gateId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='src.Admin')),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='src.User')),
            ],
        ),
    ]
