# Generated by Django 3.0.6 on 2020-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
