# Generated by Django 3.0.6 on 2020-06-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20200617_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
