# Generated by Django 3.0.6 on 2020-06-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200618_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
