# Generated by Django 3.0.6 on 2020-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_temporaryuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='mail',
            field=models.EmailField(max_length=320),
        ),
    ]
