# Generated by Django 3.0.6 on 2020-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20200622_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='photo',
            field=models.ImageField(default='/tempUser.png', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
