# Generated by Django 3.0.6 on 2020-06-24 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_auto_20200623_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='/tempUser.png', upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='/tempUser.png', upload_to='gallery')),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='src.User')),
            ],
        ),
    ]
