# Generated by Django 3.0.6 on 2020-06-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_imagegallery_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='gateId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='src.Admin'),
        ),
    ]
