# Generated by Django 3.0.6 on 2020-06-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20200626_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='gateId',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='gateId',
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='gateId1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='gateId2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='mailDue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gateId1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gateId2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='mailDue',
            field=models.IntegerField(default=0),
        ),
    ]
