# Generated by Django 3.0.6 on 2020-06-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_auto_20200627_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=1000, null=True)),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='src.User')),
            ],
        ),
    ]
